[jupiter.registry.wh]
    connectTimeout = "1s"
    endpoints=["14.29.207.63:2379"]
    secure = false
[jupiter.client.etcdserver]
    address = "etcd:///main"
    balancerName = "round_robin" # 默认值
    block =  false # 默认值
    dialTimeout = "0s" # 默认值
